import { Motorcycle } from "@/types";

export const motorcycles: Motorcycle[] = [
  {
    id: "1",
    slug: "velocity-v1",
    model: "Velocity V1",
    type: "Sport",
    image: "/images/motorcycles/velocity-V1-1.avif",
    images: [
      "/images/motorcycles/velocity-V1-1.avif",
      "/images/motorcycles/velocity-V1-2.avif",
      "/images/motorcycles/velocity-V1-3.avif",
    ],
    price: 250000,
    engine: "V-Twin 1200cc",
    horsepower: 145,
    torque: 98,
    weight: 198,
    topSpeed: 280,
    acceleration: "0-100 in 3.2s",
    fuelCapacity: "16 L",
    colors: [
      "Matte Black",
      "Racing Red",
      "Metallic Silver",
      "Midnight Blue",
      "Gold",
    ],
    description:
      "The Velocity V1 is the ultimate expression of speed and precision. Crafted for those who demand the best.",
    features: [
      "Advanced Traction Control",
      "Cornering ABS",
      "Quick Shifter",
      "LED Lighting",
    ],
    specifications: {
      engine: "V-Twin 1200cc",
      power: "145 HP",
      torque: "98 Nm",
      weight: "198 kg",
      fuelCapacity: "16 L",
      topSpeed: "280 km/h",
      acceleration: "0-100 in 3.2s",
    },
    relatedModels: ["velocity-v2", "velocity-t1", "velocity-c1"],
  },
  {
    id: "2",
    slug: "velocity-v2",
    model: "Velocity V2",
    type: "Touring",
    image: "/images/motorcycles/velocity-v2-1.svg",
    images: [
      "/images/motorcycles/velocity-v2-1.svg",
      "/images/motorcycles/velocity-v2-2.svg",
    ],
    price: 230000,
    engine: "Inline-4 1100cc",
    horsepower: 130,
    torque: 102,
    weight: 215,
    topSpeed: 260,
    acceleration: "0-100 in 3.8s",
    fuelCapacity: "18 L",
    colors: ["Matte Black", "Pearl White", "Champagne Gold", "Midnight Blue"],
    description:
      "Tour long distances with confidence. Velocity V2 blends comfort and power for every horizon.",
    features: [
      "Adaptive Cruise Control",
      "LED Matrix Headlights",
      "Integrated GPS",
      "Premium Audio",
    ],
    specifications: {
      engine: "Inline-4 1100cc",
      power: "130 HP",
      torque: "102 Nm",
      weight: "215 kg",
      fuelCapacity: "18 L",
      topSpeed: "260 km/h",
      acceleration: "0-100 in 3.8s",
    },
    relatedModels: ["velocity-v1", "velocity-a1", "velocity-c1"],
  },
  {
    id: "3",
    slug: "velocity-c1",
    model: "Velocity C1",
    type: "Cruiser",
    image: "/images/motorcycles/velocity-C1-1.avif",
    images: [
      "/images/motorcycles/velocity-C1-1.avif",
      "/images/motorcycles/velocity-C1-2.avif",
    ],
    price: 210000,
    engine: "V-Twin 1400cc",
    horsepower: 125,
    torque: 110,
    weight: 240,
    topSpeed: 230,
    acceleration: "0-100 in 4.4s",
    fuelCapacity: "19 L",
    colors: ["Matte Black", "Copper", "Metallic Silver", "Ivory White"],
    description:
      "A refined cruiser with commanding presence. Velocity C1 turns every ride into a statement.",
    features: [
      "Adaptive Suspension",
      "Custom Exhaust",
      "Premium Leather",
      "Ride Modes",
    ],
    specifications: {
      engine: "V-Twin 1400cc",
      power: "125 HP",
      torque: "110 Nm",
      weight: "240 kg",
      fuelCapacity: "19 L",
      topSpeed: "230 km/h",
      acceleration: "0-100 in 4.4s",
    },
    relatedModels: ["velocity-v1", "velocity-t1", "velocity-a1"],
  },
  {
    id: "4",
    slug: "velocity-a1",
    model: "Velocity A1",
    type: "Adventure",
    image: "/images/motorcycles/velocity-a1-1.avif",
    images: [
      "/images/motorcycles/velocity-a1-1.avif",
      "/images/motorcycles/velocity-a1-2.avif",
    ],
    price: 240000,
    engine: "Parallel Twin 1000cc",
    horsepower: 120,
    torque: 105,
    weight: 225,
    topSpeed: 245,
    acceleration: "0-100 in 4.0s",
    fuelCapacity: "20 L",
    colors: ["Desert Sand", "Midnight Blue", "Graphite Grey", "Racing Red"],
    description:
      "Built for terrain and adrenaline. Velocity A1 delivers rugged control and premium luxury.",
    features: [
      "Off-Road Traction",
      "Cornering ABS",
      "GPS Navigation",
      "Riding Modes",
    ],
    specifications: {
      engine: "Parallel Twin 1000cc",
      power: "120 HP",
      torque: "105 Nm",
      weight: "225 kg",
      fuelCapacity: "20 L",
      topSpeed: "245 km/h",
      acceleration: "0-100 in 4.0s",
    },
    relatedModels: ["velocity-v2", "velocity-v1", "velocity-e1"],
  },
  {
    id: "5",
    slug: "velocity-e1",
    model: "Velocity E1",
    type: "Electric",
    image: "/images/motorcycles/velocity-e1-1.svg",
    images: [
      "/images/motorcycles/velocity-e1-1.svg",
      "/images/motorcycles/velocity-e1-2.svg",
    ],
    price: 270000,
    engine: "Electric Twin Motor",
    horsepower: 155,
    torque: 160,
    weight: 210,
    topSpeed: 260,
    acceleration: "0-100 in 2.9s",
    fuelCapacity: "N/A",
    colors: [
      "Phantom Black",
      "Solar Orange",
      "Arctic White",
      "Stainless Steel",
    ],
    description:
      "An electric masterpiece designed to dominate both the road and the future.",
    features: [
      "Instant Torque",
      "Regenerative Braking",
      "Smart Display",
      "Adaptive Ride Modes",
    ],
    specifications: {
      engine: "Electric Twin Motor",
      power: "155 HP",
      torque: "160 Nm",
      weight: "210 kg",
      fuelCapacity: "N/A",
      topSpeed: "260 km/h",
      acceleration: "0-100 in 2.9s",
    },
    relatedModels: ["velocity-v1", "velocity-a1", "velocity-t1"],
  },
];
